"""primeira

Revision ID: c1593e1e6db9
Revises: 
Create Date: 2022-08-29 17:25:07.288762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1593e1e6db9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingrediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingrediente_id'), 'ingrediente', ['id'], unique=False)
    op.create_table('opcional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opcional_id'), 'opcional', ['id'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_id'), 'status', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('burger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('preco', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('carne_id', sa.Integer(), nullable=True),
    sa.Column('pao_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carne_id'], ['ingrediente.id'], ),
    sa.ForeignKeyConstraint(['pao_id'], ['ingrediente.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_burger_id'), 'burger', ['id'], unique=False)
    op.create_table('burger_opcionais',
    sa.Column('burger_id', sa.Integer(), nullable=True),
    sa.Column('opcional_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['burger_id'], ['burger.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opcional_id'], ['opcional.id'], ),
    sa.UniqueConstraint('burger_id', 'opcional_id', name='burguer_opcional_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('burger_opcionais')
    op.drop_index(op.f('ix_burger_id'), table_name='burger')
    op.drop_table('burger')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_status_id'), table_name='status')
    op.drop_table('status')
    op.drop_index(op.f('ix_opcional_id'), table_name='opcional')
    op.drop_table('opcional')
    op.drop_index(op.f('ix_ingrediente_id'), table_name='ingrediente')
    op.drop_table('ingrediente')
    # ### end Alembic commands ###
