version: '3.8'

services:

  backend:
    build:
        dockerfile: ./fastapi.dev.dockerfile
        context: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/src:/src
    env_file:
      - ./.envs/.fastapi.dev
    command: uvicorn server:app --reload --host 0.0.0.0 --port 5000
    networks:
    - minha-network
    depends_on:
      - db
    restart: on-failure

  frontend:
    build:
        dockerfile: ./vue.dev.dockerfile
        context: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    env_file:
      - ./.envs/.vue.dev
    ports:
      - 8080:8080
    networks:
    - minha-network
    depends_on:
      - backend
    restart: on-failure

  db:
    image: postgres:13.4-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user_db
      - POSTGRES_PASSWORD=pass_db
      - POSTGRES_DB=db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
    - minha-network
    restart: on-failure


volumes:
  postgres_data:

networks: 
    minha-network:
        driver: bridge